# Generated by Django 3.0.5 on 2020-06-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
