# Generated by Django 3.0.5 on 2020-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_auto_20200607_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_boy_blank.jpg', null=True, upload_to='pics'),
        ),
    ]
