# Generated by Django 3.0.5 on 2020-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_auto_20200607_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
