# Generated by Django 3.0.5 on 2020-06-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_auto_20200607_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
